#!/bin/sh
#
### BEGIN INIT INFO
# Provides:		lighthouse
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Start and stop the lighthouse daemon
### END INIT INFO
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/lighthouse
NAME=lighthouse
DESC="lighthouse beacon node"
PIDFILE=/var/run/lighthouse.pid
LOGFILE=/tmp/lighthouse.log

# dd if=/dev/urandom bs=32 count=1 2>/dev/null | hexdump -v -e '1/1 "%02x"' > /var/volatile/jwt.hex
start() {
	echo -n "Starting $DESC: "
	mount -o remount,size=90% /var/volatile
	echo "0x4c5a4856e3873434d51de798c8e4f17ca2dcc2ccd42cb72c8446db819fe69489" > /var/volatile/jwt.hex
	start-stop-daemon -S -p $PIDFILE -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
		bn \
        --eth1 \
        --checkpoint-sync-url https://mainnet.checkpoint.sigp.io \
        --execution-endpoint http://localhost:8551 \
        --http-allow-sync-stalled \
        --jwt-secrets="/var/volatile/jwt.hex" \
        --always-prepare-payload \
		--listen-address 0.0.0.0 \
		--log-format JSON \
        --prepare-payload-lookahead 8000 \
        --port 9000 \
        --http \
        --http-port 3500 \
        --enr-udp-port=9000 \
        --enr-tcp-port=9000 \
        --discovery-port=9000 \
        --disable-deposit-contract-sync \
        -d /var/volatile/lighthouse \
		2>&1 | tee ${LOGFILE}"
	echo "$NAME."
}

stop() {
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
}
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
exit 0
