#!/bin/sh
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start HAProxy service
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=haproxy
DESC="HAProxy Service"
LOG_DIR=/var/log/containers
LOGFILE="$LOG_DIR/haproxy.log"
HAPROXY_VERSION=3.0.6@sha256:0f3127e63b00982c3f12b2a9a17ecbd0595003a191ec1cb403741a692f7a39a9
HAPROXY_ENV_FILE=/etc/haproxy/haproxy.env
HAPROXY_CONTAINER_USERID=99

start_haproxy() {
    podman run -dt --rm --restart on-failure --name $NAME \
        -v /etc/haproxy:/usr/local/etc/haproxy:ro \
        -v /var/run/haproxy:/var/run/haproxy \
        --log-opt path=$LOGFILE --log-opt max-size=10mb \
        --net host --cap-add=NET_BIND_SERVICE \
        --env-file $HAPROXY_ENV_FILE \
        docker.io/haproxy:$HAPROXY_VERSION
}

start() {
    echo -n "Starting $DESC: "
    echo "Starting $DESC" > /var/volatile/system-api.fifo
    chmod 644 /etc/haproxy/haproxy.cfg
    install -d -m 755 $LOG_DIR
    install -d -m 750 -o $HAPROXY_CONTAINER_USERID -g $HAPROXY_CONTAINER_USERID /var/run/haproxy/
    if [ ! -f $HAPROXY_ENV_FILE ]; then
        install -m 640 -o $HAPROXY_CONTAINER_USERID -g $HAPROXY_CONTAINER_USERID /dev/null $HAPROXY_ENV_FILE
    fi
    mkdir -p /usr/local/etc/haproxy
    ln -sf /etc/haproxy/certs /usr/local/etc/haproxy
    ln -sf /etc/haproxy/static /usr/local/etc/haproxy
    start_haproxy
    chmod 644 $LOGFILE
    echo "$NAME."
}

stop() {
    echo "Stopping $DESC" | tee -a /var/volatile/system-api.fifo
    podman stop $NAME
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
