#!/bin/sh
### BEGIN INIT INFO
# Provides:          autoprovisioning-agent
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Autoprovisioning Agent at boot time
# Description:       Enable Autoprovisioning Agent service.
### END INIT INFO

DAEMON=/usr/bin/autoprovisioning-agent
NAME=autoprovisioning-agent
DESC="Autoprovisioning Agent"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
ULIMIT_FD=65536

source /etc/autoprovisioning-agent.conf

start() {
    echo -n "Starting $DESC: "
    echo "Starting $DESC" > /var/volatile/system-api.fifo
    start-stop-daemon -S --make-pidfile -p $PIDFILE -m -b --exec /bin/sh -- -c "ulimit -n $ULIMIT_FD; exec $DAEMON >> $LOGFILE 2>&1"
    echo "$NAME."
}

stop() {
    echo -n "Stopping $DESC: "
    echo "Stopping $DESC" > /var/volatile/system-api.fifo
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
    echo "$NAME."
}

restart() {
    echo "Restarting $DESC: "
    echo "Restarting $DESC" > /var/volatile/system-api.fifo
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
