#!/bin/sh
### BEGIN INIT INFO
# Provides:          reth-sync
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Sync data using rclone
# Description:       Runs rclone sync script to synchronize data from R2 storage
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="Rclone Sync Service"
NAME=reth-sync
LOGFILE=/tmp/reth-sync.log
RCLONE_CONFIG=/etc/rclone.conf
RETH_DIR=/persistent/reth

start() {
	echo -n "Starting $DESC: "
	# fetch the env variables that contains the amazon s3 credentials and the endpoint
	source /usr/bin/setup_env.sh

    LATEST_META=$(rclone --config $RCLONE_CONFIG cat r2:chain-db-snapshots/reth-mainnet-full/latest_version.meta.txt)
    rclone sync --config $RCLONE_CONFIG -v -P --transfers=20 --multi-thread-streams 30 \
	--contimeout=10m --retries 10 --retries-sleep 60 --error-on-no-transfer --update --fast-list \
	--delete-during --disable-http2 --no-gzip-encoding \
	--exclude 'files.txt' r2:chain-db-snapshots/reth-mainnet-full/$LATEST_META/ $RETH_DIR
	echo "Reth is synced with the latest meta version: $LATEST_META"
	echo "$NAME."
}


case "$1" in
  start)
        start > $LOGFILE 2>&1
        ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N start" >&2
	exit 1
	;;
esac
exit 0
