#!/bin/sh
### BEGIN INIT INFO
# Provides:          bid-scraper
# Required-Start:    $network $remote_fs fetch-config reth-sync
# Required-Stop:     $network $remote_fs
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: bid-scraper
# Description:       Start and stop the bid-scraper daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/bid-scraper
NAME=bid-scraper
DESC="Bid Scraper"
PIDFILE=/var/run/bid-scraper.pid
LOGFILE=/var/log/bid-scraper.log
BID_SCRAPER_USER=bid-scraper
BID_SCRAPER_GROUP=bid-scraper
BID_SCRAPER_CONFIG=/etc/bid-scraper/config.toml

source /etc/bid-scraper/env

start() {
  echo -n "Starting $DESC: "
  echo "Starting $DESC" > /var/volatile/system-api.fifo

  # Ensure the bid-scraper log file exists and has correct permissions
  touch $LOGFILE
  chown $BID_SCRAPER_USER:$BID_SCRAPER_GROUP $LOGFILE

  start-stop-daemon -S --make-pidfile -p $PIDFILE -c $BID_SCRAPER_USER:$BID_SCRAPER_GROUP -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
    ${BID_SCRAPER_CONFIG} \
    2>&1 | tee -a ${LOGFILE}"

  echo "$NAME"
}

stop() {
    echo "Stopping $NAME"
    echo "Stopping $NAME" > /var/volatile/system-api.fifo
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        # Find all child processes of the shell process
        PIDS="$PID $(pgrep -P $PID)"

        # Send SIGTERM to all processes
        for pid in $PIDS; do
            kill -TERM $pid 2>/dev/null
        done

        # Send SIGKILL to any remaining processes
        for pid in $PIDS; do
            kill -KILL $pid 2>/dev/null
        done

        rm -f $PIDFILE
    else
        echo "$PIDFILE not found, $NAME may not be running"
    fi

    echo "$NAME stopped"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
  N=/etc/init.d/$NAME
  echo "Usage: $N {start|stop|restart|reload}" >&2
  exit 1
  ;;
esac
exit 0
