#!/bin/sh
### BEGIN INIT INFO
# Provides:          flowproxy
# Required-Start:    $network $remote_fs $syslog fetch-config
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Orderflow Proxy at boot time
# Description:       Enable Orderflow Proxy service.
### END INIT INFO

DAEMON=/usr/bin/flowproxy
NAME=flowproxy
DESC="FlowProxy"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
FLOWPROXY_USER=flowproxy
FLOWPROXY_GROUP=flowproxy
ULIMIT_FD=1048576
FLOWPROXY_DIR=/persistent/flowproxy
SYSTEM_API_FIFO=/var/volatile/system-api.fifo

source /etc/flowproxy/env

start() {
    echo -n "Starting $DESC: "
    echo "Starting $DESC" > $SYSTEM_API_FIFO
    mkdir -p "$FLOWPROXY_DIR"
    chown -R $FLOWPROXY_USER:$FLOWPROXY_GROUP $FLOWPROXY_DIR
    start-stop-daemon -S --make-pidfile -p $PIDFILE -c $FLOWPROXY_USER:$FLOWPROXY_GROUP -m -b --exec /bin/sh -- -c "ulimit -n $ULIMIT_FD; exec $DAEMON >> $LOGFILE 2>&1"
    echo "$NAME."
}

stop() {
    echo -n "Stopping $DESC: "
    echo "Stopping $DESC" > $SYSTEM_API_FIFO
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
    echo "$NAME."
}

restart() {
    echo "Restarting $DESC: "
    echo "Restarting $DESC" > $SYSTEM_API_FIFO
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0