#!/bin/sh
### BEGIN INIT INFO
# Provides:          rbuilder-bidding
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start rbuilder bidding service
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=rbuilder-bidding
DESC="Builder Bidding Service"
LOGFILE=/var/log/containers/rbuilder-bidding.log
RBUILDER_USER=rbuilder
RBUILDER_BIDDING_VERSION=0.4.1@sha256:9a27046ad3d11a38c8f67c98dbc8fb59c2a545f18f2e809e5accdfe8df7d5b8b
ETH_GROUP=eth

source /etc/rbuilder-bidding/rbuilder-bidding-token

start_builder_bidding() {
    podman run -dt --rm --restart on-failure --name $NAME \
        -v /etc/rbuilder-bidding:/rbuilder-bidding \
        -v /var/run/rbuilder:/var/run/rbuilder \
        --user $(id -u rbuilder):$(id -g rbuilder) \
        --log-opt path=$LOGFILE --log-opt max-size=10mb \
        ghcr.io/flashbots/rbuilder-bidding-service:$RBUILDER_BIDDING_VERSION /rbuilder-bidding/bidding-service.toml
}

start() {
    echo -n "Starting $DESC: "
    echo "Starting $DESC" > /var/volatile/system-api.fifo

    # Ensure the rbuilder log file exists and has correct permissions
    touch $LOGFILE
    chown $RBUILDER_USER:$ETH_GROUP $LOGFILE

    echo $GITHUB_TOKEN | podman login ghcr.io -u flashbots --password-stdin

    mkdir -p /var/run/rbuilder /var/log/containers
    chown -R $RBUILDER_USER:$RBUILDER_USER /var/run/rbuilder

    start_builder_bidding
    echo "$NAME."
}

stop() {
    echo "Stopping $DESC" | tee -a /var/volatile/system-api.fifo
    podman stop $NAME
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
