#!/bin/sh
### BEGIN INIT INFO
# Provides:          rbuilder-bidding
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start rbuilder bidding service
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=rbuilder-bidding
DESC="Builder Bidding Service"
LOG_DIR=/var/log/containers
LOGFILE="$LOG_DIR/rbuilder-bidding.log"
RUN_DIR=/var/run/rbuilder
RBUILDER_USER=rbuilder
RBUILDER_BIDDING_VERSION=1.2.28@sha256:3a9bf2b7a13e8b02e6dc47ed42842c4c37839c00e47e2521ac83d578e579b77f
ETH_GROUP=eth

source /etc/rbuilder-bidding/rbuilder-bidding-token

start_builder_bidding() {
    podman run -dt --rm --restart on-failure --name $NAME \
        -v /etc/rbuilder-bidding:/rbuilder-bidding \
        -v $RUN_DIR:$RUN_DIR \
        -v /dev/shm:/dev/shm \
        -v /tmp/iceoryx2:/tmp/iceoryx2 \
        --user $(id -u rbuilder):$(id -g rbuilder) \
        --log-opt path=$LOGFILE \
        --network=none \
        ghcr.io/flashbots/rbuilder-bidding-service:$RBUILDER_BIDDING_VERSION /rbuilder-bidding/bidding-service.toml
}

start() {
    echo -n "Starting $DESC: "
    echo "Starting $DESC" > /var/volatile/system-api.fifo

    echo $GITHUB_TOKEN | podman login ghcr.io -u flashbots --password-stdin

    install -d -m 755 $LOG_DIR $RUN_DIR
    chown -R $RBUILDER_USER:$RBUILDER_USER $RUN_DIR

    mkdir -p /tmp/iceoryx2
    chown $RBUILDER_USER:$ETH_GROUP /tmp/iceoryx2

    start_builder_bidding
    chmod 644 $LOGFILE
    echo "$NAME."
}

stop() {
    echo "Stopping $DESC" | tee -a /var/volatile/system-api.fifo
    podman stop $NAME
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
