#!/bin/sh
### BEGIN INIT INFO
# Provides:          reth
# Required-Start:    $network $remote_fs reth-sync
# Required-Stop:     $network $remote_fs
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Reth Node
# Description:       Start and stop the reth daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/reth
NAME=reth
DESC="Reth Node"
PIDFILE=/var/run/reth.pid
LOGFILE=/tmp/reth.log
RETH_USER=reth
RETH_GROUP=reth
RETH_DIR=/persistent/reth

start() {
	echo -n "Starting $DESC: "
	# Source the setup.env file
	if [ -f /usr/bin/setup_env.sh ]; then
		source /usr/bin/setup_env.sh
	fi

	# Ensure the RETH_DIR exists and has correct permissions
	mkdir -p $RETH_DIR
	chown $RETH_USER:$RETH_GROUP $RETH_DIR

	# Set JWT_SECRET, use environment variable if set, otherwise use hardcoded value
	JWT_SECRET=${JWT_SECRET:-"0x4c5a4856e3873434d51de798c8e4f17ca2dcc2ccd42cb72c8446db819fe69489"}

	mount -o remount,size=90% /var/volatile
	echo "$JWT_SECRET" > /var/volatile/jwt.hex
	chown ${RETH_USER}:${RETH_GROUP} /var/volatile/jwt.hex
	start-stop-daemon -S -p $PIDFILE -c $RETH_USER:$RETH_GROUP -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
		node \
		--full \
		--datadir "$RETH_DIR" \
		--authrpc.addr 0.0.0.0 \
		--authrpc.jwtsecret "/var/volatile/jwt.hex" \
		--authrpc.port 8551 \
		--http \
		--http.addr 0.0.0.0 \
		--http.port 8545 \
		--http.api "eth,net,web3,trace,rpc,debug,txpool" \
		--ws \
		--ws.addr 0.0.0.0 \
		--ws.port 8546 \
		--ws.api "eth,net,trace,web3,rpc,debug,txpool" \
		--log.stdout.format json \
		--log.file.max-files 0 \
		2>&1 | tee ${LOGFILE}"
	echo "$NAME."
}

stop() {
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
}
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
exit 0
