#!/bin/sh
### BEGIN INIT INFO
# Provides:          rebalancer
# Required-Start:    $network $remote_fs fetch-config
# Required-Stop:     $network $remote_fs
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: rebalancer
# Description:       Start and stop the rebalancer daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/rbuilder-rebalancer
NAME=rbuilder-rebalancer
DESC="rbuilder rebalancer"
PIDFILE=/var/run/rbuilder-rebalancer.pid
LOGFILE=/var/log/rbuilder-rebalancer.log
REBALANCER_USER=rbuilder-rebalancer
REBALANCER_GROUP=rbuilder-rebalancer
REBALANCER_CONFIG=/etc/rbuilder-rebalancer/config.toml

source /etc/rbuilder-rebalancer/env

start() {
  echo -n "Starting $DESC: "
  echo "Starting $DESC" > /var/volatile/system-api.fifo

  # Ensure the rebalancer log file exists and has correct permissions
  touch $LOGFILE
  chown $REBALANCER_USER:$REBALANCER_USER $LOGFILE

  start-stop-daemon -S --make-pidfile -p $PIDFILE -c $REBALANCER_USER:$REBALANCER_USER -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
    ${REBALANCER_CONFIG} \
    2>&1 | tee -a ${LOGFILE}"

  echo "$NAME"
}

stop() {
    echo "Stopping $NAME"
    echo "Stopping $NAME" > /var/volatile/system-api.fifo
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        # Find all child processes of the shell process
        PIDS="$PID $(pgrep -P $PID)"

        # Send SIGTERM to all processes
        for pid in $PIDS; do
            kill -TERM $pid 2>/dev/null
        done

        # Send SIGKILL to any remaining processes
        for pid in $PIDS; do
            kill -KILL $pid 2>/dev/null
        done

        rm -f $PIDFILE
    else
        echo "$PIDFILE not found, $NAME may not be running"
    fi

    echo "$NAME stopped"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
  N=/etc/init.d/$NAME
  echo "Usage: $N {start|stop|restart|reload}" >&2
  exit 1
  ;;
esac

exit 0
